version: "3.8"

services:
  backend:
    build: .
    container_name: my-backend
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/maintenance
    volumes:
      - .:/app
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: your_secure_password

volumes:
  mongodb_data:
